### ISSUE TITLE
How to verify if it's working or not?

### ISSUE THREAD

**Issue by hexchain** [intel/dptf#30]
I've just installed this program on my system (Arch Linux, XPS 9360) and I see logs like this every few seconds in the journal:

```
INFO:[<ACTION>ActionSystemSet@esif_uf_action_system.c#165]<1586383697211 ms>: SYSTEM_HIBERNATE command received - system hibernate...
INFO:[<ACTION>ActionSystemSet@esif_uf_action_system.c#165]<1586383712217 ms>: SYSTEM_HIBERNATE command received - system hibernate...
```

Apparently my system is not hibernating every few seconds. Is this supposed to be correct? Is there any other way to see if it is actually working or not?

**Comment by bbian** [comment]
It's possible that your XPS 9360 has low hibernation trip point settings that would cause DPTF to constantly try to start the hibernation process. The actual command to send system to hibernate is "pm-hibernate" (can be found in https://github.com/intel/dptf/blob/master/ESIF/Products/ESIF_UF/Sources/esif_uf_ccb_system.h). This however may or may not work depending on OS settings. 

You can find out the actual hibernation trip points by going through this document https://www.kernel.org/doc/Documentation/thermal/sysfs-api.txt and search for "trip_point_[0-*]_type". The type for hibernation trip points is called "hot".

You may not see such problems under Windows because Windows uses a different set of configurations that OEMs specifically made for Windows, so there is likelihood that the Windows thermal settings and the settings for other OS may not match.

**Comment by hexchain** [comment]
Thanks for the explanation.

After checking sysfs, there does seem to be a suspicious thermal zone `/sys/class/thermal/thermal_zone7`, with the type of `B0D4`, whose `trip_point_1_type` is `hot` and `trip_point_1_temp` is `-273250`.
